[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@poseidon2/contracts/=lib/poseidon2-evm/src/"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
